// ── packages/contracts/src/types/api.ts ─────────────────────────────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs from packages/contracts/openapi/openapi.yaml
// and packages/contracts/schemas/*.json.
//

/** All documented error codes from the API contract */
export type ErrorCode =
  | 'PHONE_REQUIRED'
  | 'INVALID_PHONE'
  | 'COOLDOWN'
  | 'RATE_LIMITED'
  | 'IP_RATE_LIMITED'
  | 'SEND_FAILED'
  | 'SMS_UNAVAILABLE'
  | 'PARAMS_REQUIRED'
  | 'VERIFICATION_EXPIRED'
  | 'INVALID_CODE'
  | 'ATTEMPTS_EXCEEDED'
  | 'VERIFY_FAILED'
  | 'UNAUTHORIZED'
  | 'SESSION_REVOKED'
  | 'SESSION_EXPIRED'
  | 'USER_NOT_FOUND'
  | 'NOT_FOUND'

/** Standard error response for all endpoints */
export interface ErrorResponse {
  error: string;
  code: ErrorCode;
}

export interface HealthResponse {
  status: "ok";
}

export interface LogoutResponse {
  success: true;
}

export interface SendCodeRequest {
  phone: string;
}

export interface SendCodeResponse {
  success: true;
  debugCode?: string;
}

export interface SessionResponse {
  user: User;
}

export interface User {
  id: string;
  normalizedPhone: string;
  createdAt: string;
  lastLoginAt: string;
  isLoggedIn: true;
  hasFullAccess: boolean;
}

export interface VerifyCodeRequest {
  phone: string;
  code: string;
}

export interface VerifyCodeResponse {
  token: string;
  user: User;
}

// ── Per-endpoint response types ───────────────────────────────────

/** GET /api/health — Health */
export type HealthEndpoint = {
  method: 'GET';
  path: '/api/health';
  response: HealthResponse;
  error: ErrorResponse;
};

/** POST /api/auth/send-code — SendCode */
export type SendCodeEndpoint = {
  method: 'POST';
  path: '/api/auth/send-code';
  response: SendCodeResponse;
  error: ErrorResponse;
};

/** POST /api/auth/verify-code — VerifyCode */
export type VerifyCodeEndpoint = {
  method: 'POST';
  path: '/api/auth/verify-code';
  response: VerifyCodeResponse;
  error: ErrorResponse;
};

/** GET /api/auth/session — Session */
export type SessionEndpoint = {
  method: 'GET';
  path: '/api/auth/session';
  response: SessionResponse;
  error: ErrorResponse;
};

/** POST /api/auth/logout — Logout */
export type LogoutEndpoint = {
  method: 'POST';
  path: '/api/auth/logout';
  response: LogoutResponse;
  error: ErrorResponse;
};

