// ── packages/contracts/src/tests/contract-tests.template.ts ───────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// Contract test templates — one describe-block per endpoint.
// Run against a running backend instance (default: http://localhost:3000).
//
// Usage:
//   npm install --save-dev node-fetch@2 (or use native fetch in Node 18+)
//   node --test packages/contracts/src/tests/contract-tests.template.ts
//
// Replace BASE_URL as needed for your environment.
//

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

const BASE_URL = process.env.CONTRACT_TEST_URL || 'http://localhost:3000';

// ── Helper: typed fetch ──────────────────────────────────────────────

async function apiFetch<T>(method: string, path: string, body?: unknown, headers?: Record<string, string>): Promise<{ status: number; data: T }> {
  const url = `${BASE_URL}${path}`;
  const res = await fetch(url, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...headers,
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  return { status: res.status, data };
}

describe('GET /api/health — Health', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('GET', '/api/health');
    assert.equal(status, 200);
    assert.ok(data);
  });

});

describe('POST /api/auth/send-code — SendCode', () => {
  it('should return 200 with valid shape', async () => {
    const body = {"phone":"test"};
    const { status, data } = await apiFetch('POST', '/api/auth/send-code', body);
    assert.equal(status, 200);
    assert.ok(data);
  });


  it.todo("should return 503 with code \"SMS_UNAVAILABLE\"");
  it.todo("should return 400 with code \"PHONE_REQUIRED\"");
  it.todo("should return 400 with code \"INVALID_PHONE\"");
  it.todo("should return 429 with code \"COOLDOWN\"");
  it.todo("should return 429 with code \"RATE_LIMITED\"");
});

describe('POST /api/auth/verify-code — VerifyCode', () => {
  it('should return 200 with valid shape', async () => {
    const body = {"phone":"test","code":"test"};
    const { status, data } = await apiFetch('POST', '/api/auth/verify-code', body);
    assert.equal(status, 200);
    assert.ok(data);
  });


  it.todo("should return 400 with code \"PARAMS_REQUIRED\"");
  it.todo("should return 400 with code \"VERIFICATION_EXPIRED\"");
  it.todo("should return 400 with code \"INVALID_CODE\"");
  it.todo("should return 400 with code \"ATTEMPTS_EXCEEDED\"");
});

describe('GET /api/auth/session — Session', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('GET', '/api/auth/session');
    assert.equal(status, 200);
    assert.ok(data);
  });


  it.todo("should return 401 with code \"UNAUTHORIZED\"");
  it.todo("should return 401 with code \"SESSION_REVOKED\"");
  it.todo("should return 401 with code \"SESSION_EXPIRED\"");
});

describe('POST /api/auth/logout — Logout', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('POST', '/api/auth/logout');
    assert.equal(status, 200);
    assert.ok(data);
  });

});
