// ── packages/contracts/src/tests/contract-tests.template.ts ───────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// Contract test templates — one describe-block per endpoint.
// Run against a running backend instance (default: http://localhost:3000).
//
// Usage:
//   npm install --save-dev node-fetch@2 (or use native fetch in Node 18+)
//   node --test packages/contracts/src/tests/contract-tests.template.ts
//
// Replace BASE_URL as needed for your environment.
//

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

const BASE_URL = process.env.CONTRACT_TEST_URL || 'http://localhost:3000';

// ── Helper: typed fetch ──────────────────────────────────────────────

async function apiFetch<T>(method: string, path: string, body?: unknown, headers?: Record<string, string>): Promise<{ status: number; data: T }> {
  const url = `${BASE_URL}${path}`;
  const res = await fetch(url, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...headers,
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  return { status: res.status, data };
}

describe('GET /api/health — Health', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('GET', '/api/health');
    assert.equal(status, 200);
    assert.ok(data);
  });

});

describe('POST /api/auth/send-code — SendCode', () => {
  it('should return 200 with valid shape', async () => {
    const body = {"phone":"test"};
    const { status, data } = await apiFetch('POST', '/api/auth/send-code', body);
    assert.equal(status, 200);
    assert.ok(data);
  });

  it('should return error codes on failure', async () => {
    // TODO: implement test cases for each error scenario:
    //   - status 503, code "SMS_UNAVAILABLE"
    //   - status 400, code "PHONE_REQUIRED"
    //   - status 400, code "INVALID_PHONE"
    //   - status 429, code "COOLDOWN"
    //   - status 429, code "RATE_LIMITED"
  });
});

describe('POST /api/auth/verify-code — VerifyCode', () => {
  it('should return 200 with valid shape', async () => {
    const body = {"phone":"test","code":"test"};
    const { status, data } = await apiFetch('POST', '/api/auth/verify-code', body);
    assert.equal(status, 200);
    assert.ok(data);
  });

  it('should return error codes on failure', async () => {
    // TODO: implement test cases for each error scenario:
    //   - status 400, code "PARAMS_REQUIRED"
    //   - status 400, code "VERIFICATION_EXPIRED"
    //   - status 400, code "INVALID_CODE"
    //   - status 400, code "ATTEMPTS_EXCEEDED"
  });
});

describe('GET /api/auth/session — Session', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('GET', '/api/auth/session');
    assert.equal(status, 200);
    assert.ok(data);
  });

  it('should return error codes on failure', async () => {
    // TODO: implement test cases for each error scenario:
    //   - status 401, code "UNAUTHORIZED"
    //   - status 401, code "SESSION_REVOKED"
    //   - status 401, code "SESSION_EXPIRED"
  });
});

describe('POST /api/auth/logout — Logout', () => {
  it('should return 200 with valid shape', async () => {
    const { status, data } = await apiFetch('POST', '/api/auth/logout');
    assert.equal(status, 200);
    assert.ok(data);
  });

});
