// ── packages/contracts/src/dto/validators.ts ──────────────────────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// Backend request DTO validators derived from JSON Schema definitions.
// Pure functions — no external validation library required.
//
// Each validator returns { valid: true, data: ParsedType } on success,
// or { valid: false, errors: string[] } on failure.
//
// NOTES:
// - Schema `const` values are converted to assertions (exact-match).
// - Date-time format is validated as ISO 8601 string presence only.
//

import type { HealthResponse,
  LogoutResponse,
  SendCodeRequest,
  SendCodeResponse,
  SessionResponse,
  User,
  VerifyCodeRequest,
  VerifyCodeResponse } from '../types/api';

export { ErrorCode } from '../types/api';
export type { ErrorResponse } from '../types/api';

// ── Validation helpers ───────────────────────────────────────────────

type ValidationResult<T> =
  | { valid: true; data: T }
  | { valid: false; errors: string[] };

function isString(v: unknown): v is string {
  return typeof v === 'string';
}

function isBoolean(v: unknown): v is boolean {
  return typeof v === 'boolean';
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function requiredCheck(value: unknown, name: string, errors: string[]): void {
  if (value === undefined || value === null) {
    errors.push(`${name} is required`);
  }
}

function dateTimeCheck(value: unknown, name: string, errors: string[]): void {
  if (typeof value === 'string' && !isNaN(Date.parse(value))) return;
  if (value !== undefined && value !== null) {
    errors.push(`${name} must be a valid ISO 8601 date-time string`);
  }
}

function uuidCheck(value: unknown, name: string, errors: string[]): void {
  if (typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)) return;
  if (value !== undefined && value !== null) {
    errors.push(`${name} must be a valid UUID`);
  }
}

function phonePatternCheck(value: unknown, name: string, errors: string[]): void {
  if (typeof value === 'string' && /^\+86\d{11}$/.test(value)) return;
  if (value !== undefined && value !== null) {
    errors.push(`${name} must match pattern +86 followed by 11 digits`);
  }
}

// ── Request validators ───────────────────────────────────────────────

/** Validates SendCodeRequest request body */
export function validateSendCodeRequest(input: unknown): ValidationResult<SendCodeRequest> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Request body must be a JSON object');
    return { valid: false, errors };
  }

  requiredCheck(input['phone'], 'phone', errors);

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as SendCodeRequest };
}

/** Validates VerifyCodeRequest request body */
export function validateVerifyCodeRequest(input: unknown): ValidationResult<VerifyCodeRequest> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Request body must be a JSON object');
    return { valid: false, errors };
  }

  requiredCheck(input['phone'], 'phone', errors);
  requiredCheck(input['code'], 'code', errors);

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as VerifyCodeRequest };
}

// ── Response validators ──────────────────────────────────────────────

/** Validates HealthResponse response body */
export function validateHealthResponse(input: unknown): ValidationResult<HealthResponse> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Response body must be a JSON object');
    return { valid: false, errors };
  }

  // status has const value "ok"
  if (input['status'] !== undefined && input['status'] !== "ok") {
    errors.push('status must be "ok"');
  }

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as HealthResponse };
}

/** Validates SendCodeResponse response body */
export function validateSendCodeResponse(input: unknown): ValidationResult<SendCodeResponse> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Response body must be a JSON object');
    return { valid: false, errors };
  }

  // success has const value true
  if (input['success'] !== undefined && input['success'] !== true) {
    errors.push('success must be true');
  }

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as SendCodeResponse };
}

/** Validates VerifyCodeResponse response body */
export function validateVerifyCodeResponse(input: unknown): ValidationResult<VerifyCodeResponse> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Response body must be a JSON object');
    return { valid: false, errors };
  }

  requiredCheck(input['token'], 'token', errors);
  requiredCheck(input['user'], 'user', errors);
  if (input['user'] !== undefined) {
    const nestedResult = validateUser(input['user']);
    if (!nestedResult.valid) {
      errors.push(...nestedResult.errors.map(e => 'user.' + e));
    }
  }

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as VerifyCodeResponse };
}

/** Validates SessionResponse response body */
export function validateSessionResponse(input: unknown): ValidationResult<SessionResponse> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Response body must be a JSON object');
    return { valid: false, errors };
  }

  requiredCheck(input['user'], 'user', errors);
  if (input['user'] !== undefined) {
    const nestedResult = validateUser(input['user']);
    if (!nestedResult.valid) {
      errors.push(...nestedResult.errors.map(e => 'user.' + e));
    }
  }

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as SessionResponse };
}

/** Validates LogoutResponse response body */
export function validateLogoutResponse(input: unknown): ValidationResult<LogoutResponse> {
  const errors: string[] = [];

  if (!isObject(input)) {
    errors.push('Response body must be a JSON object');
    return { valid: false, errors };
  }

  // success has const value true
  if (input['success'] !== undefined && input['success'] !== true) {
    errors.push('success must be true');
  }

  if (errors.length > 0) return { valid: false, errors };
  return { valid: true, data: input as LogoutResponse };
}
