// ── packages/contracts/src/msw/fetch-mock.ts ──────────────────────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// Pure-fetch mock adapter — zero external dependencies.
// Intercepts global fetch() to return contract fixture data.
// Drop-in alternative when MSW is not installed.
//
// Usage:
//   import { installFetchMock, uninstallFetchMock } from 'packages/contracts/src/msw/fetch-mock';
//
//   // Before running tests / during dev:
//   installFetchMock();
//
//   // Cleanup:
//   uninstallFetchMock();
//
// For a full MSW setup (with service worker), install `msw` and use `handlers.ts` instead.
//

import type { ErrorCode,
  HealthResponse,
  LogoutResponse,
  SendCodeRequest,
  SendCodeResponse,
  SessionResponse,
  User,
  VerifyCodeRequest,
  VerifyCodeResponse } from '../types/api';

// ── Fixture registry ────────────────────────────────────────────────
const FIXTURES: Record<string, unknown> = {
  'health-success': {"status":"ok"},
  'logout-success': {"success":true},
  'send-code-error-cooldown': {"error":"发送太频繁，请 42 秒后再试","code":"COOLDOWN"},
  'send-code-error-invalid-phone': {"error":"手机号格式不正确","code":"INVALID_PHONE"},
  'send-code-error-phone-required': {"error":"手机号不能为空","code":"PHONE_REQUIRED"},
  'send-code-error-rate-limited': {"error":"发送太频繁，请稍后再试","code":"RATE_LIMITED"},
  'send-code-error-sms-unavailable': {"error":"短信服务暂不可用，请稍后再试","code":"SMS_UNAVAILABLE"},
  'send-code-success-dev': {"success":true,"debugCode":"123456"},
  'send-code-success': {"success":true},
  'session-error-expired': {"error":"会话已过期","code":"SESSION_EXPIRED"},
  'session-error-revoked': {"error":"会话已失效","code":"SESSION_REVOKED"},
  'session-error-unauthorized': {"error":"未登录","code":"UNAUTHORIZED"},
  'session-success': {"user":{"id":"550e8400-e29b-41d4-a716-446655440000","normalizedPhone":"+8613800138000","createdAt":"2025-07-16T00:00:00.000Z","lastLoginAt":"2025-07-16T00:00:00.000Z","isLoggedIn":true,"hasFullAccess":false}},
  'verify-code-error-attempts-exceeded': {"error":"验证码错误或已过期","code":"ATTEMPTS_EXCEEDED"},
  'verify-code-error-expired': {"error":"验证码错误或已过期","code":"VERIFICATION_EXPIRED"},
  'verify-code-error-invalid-code': {"error":"验证码错误或已过期","code":"INVALID_CODE"},
  'verify-code-error-params-required': {"error":"手机号和验证码不能为空","code":"PARAMS_REQUIRED"},
  'verify-code-success': {"token":"a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2","user":{"id":"550e8400-e29b-41d4-a716-446655440000","normalizedPhone":"+8613800138000","createdAt":"2025-07-16T00:00:00.000Z","lastLoginAt":"2025-07-16T00:00:00.000Z","isLoggedIn":true,"hasFullAccess":false}},
};

// ── Route table ────────────────────────────────────────────────────

type RouteEntry = {
  method: string;
  path: string;
  status: number;
  fixtureKey: string;
};

const ROUTES: RouteEntry[] = [
  { method: 'GET', path: '/api/health', status: 200, fixtureKey: 'health-success' },
  { method: 'POST', path: '/api/auth/send-code', status: 200, fixtureKey: 'send-code-success' },
  { method: 'POST', path: '/api/auth/send-code', status: 503, fixtureKey: 'send-code-error-sms-unavailable' },
  { method: 'POST', path: '/api/auth/send-code', status: 200, fixtureKey: 'send-code-success-dev' },
  { method: 'POST', path: '/api/auth/send-code', status: 400, fixtureKey: 'send-code-error-phone-required' },
  { method: 'POST', path: '/api/auth/send-code', status: 400, fixtureKey: 'send-code-error-invalid-phone' },
  { method: 'POST', path: '/api/auth/send-code', status: 429, fixtureKey: 'send-code-error-cooldown' },
  { method: 'POST', path: '/api/auth/send-code', status: 429, fixtureKey: 'send-code-error-rate-limited' },
  { method: 'POST', path: '/api/auth/verify-code', status: 200, fixtureKey: 'verify-code-success' },
  { method: 'POST', path: '/api/auth/verify-code', status: 400, fixtureKey: 'verify-code-error-params-required' },
  { method: 'POST', path: '/api/auth/verify-code', status: 400, fixtureKey: 'verify-code-error-expired' },
  { method: 'POST', path: '/api/auth/verify-code', status: 400, fixtureKey: 'verify-code-error-invalid-code' },
  { method: 'POST', path: '/api/auth/verify-code', status: 400, fixtureKey: 'verify-code-error-attempts-exceeded' },
  { method: 'GET', path: '/api/auth/session', status: 200, fixtureKey: 'session-success' },
  { method: 'GET', path: '/api/auth/session', status: 401, fixtureKey: 'session-error-unauthorized' },
  { method: 'GET', path: '/api/auth/session', status: 401, fixtureKey: 'session-error-revoked' },
  { method: 'GET', path: '/api/auth/session', status: 401, fixtureKey: 'session-error-expired' },
  { method: 'POST', path: '/api/auth/logout', status: 200, fixtureKey: 'logout-success' },
];

let _originalFetch: typeof globalThis.fetch | null = null;

function mockFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
  const method = (init?.method || 'GET').toUpperCase();
  const path = new URL(url, 'http://localhost').pathname;

  const match = ROUTES.find(r => r.method === method && r.path === path);
  if (!match) {
    console.warn('[fetch-mock] No matching route:', method, path);
    return _originalFetch!(input, init);
  }

  const body = FIXTURES[match.fixtureKey];
  return Promise.resolve(
    new Response(JSON.stringify(body), {
      status: match.status,
      headers: { 'Content-Type': 'application/json' },
    })
  );
}

export function installFetchMock(): void {
  if (_originalFetch) return; // Already installed
  _originalFetch = globalThis.fetch;
  globalThis.fetch = mockFetch as typeof globalThis.fetch;
}

export function uninstallFetchMock(): void {
  if (_originalFetch) {
    globalThis.fetch = _originalFetch;
    _originalFetch = null;
  }
}
