// ── packages/contracts/src/msw/fixtures.ts ────────────────────────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// Typed fixture index — provides strongly-typed accessors for all
// mock fixture data defined in packages/contracts/fixtures/.
//

import type { ErrorCode,
  HealthResponse,
  LogoutResponse,
  SendCodeRequest,
  SendCodeResponse,
  SessionResponse,
  User,
  VerifyCodeRequest,
  VerifyCodeResponse } from '../types/api';

// ── Individual fixture exports ──────────────────────────────────────
export const healthSuccess = {
  "status": "ok"
} as const;
export const logoutSuccess = {
  "success": true
} as const;
export const sendCodeErrorCooldown = {
  "error": "发送太频繁，请 42 秒后再试",
  "code": "COOLDOWN"
} as const;
export const sendCodeErrorInvalidPhone = {
  "error": "手机号格式不正确",
  "code": "INVALID_PHONE"
} as const;
export const sendCodeErrorPhoneRequired = {
  "error": "手机号不能为空",
  "code": "PHONE_REQUIRED"
} as const;
export const sendCodeErrorRateLimited = {
  "error": "发送太频繁，请稍后再试",
  "code": "RATE_LIMITED"
} as const;
export const sendCodeErrorSmsUnavailable = {
  "error": "短信服务暂不可用，请稍后再试",
  "code": "SMS_UNAVAILABLE"
} as const;
export const sendCodeSuccessDev = {
  "success": true,
  "debugCode": "123456"
} as const;
export const sendCodeSuccess = {
  "success": true
} as const;
export const sessionErrorExpired = {
  "error": "会话已过期",
  "code": "SESSION_EXPIRED"
} as const;
export const sessionErrorRevoked = {
  "error": "会话已失效",
  "code": "SESSION_REVOKED"
} as const;
export const sessionErrorUnauthorized = {
  "error": "未登录",
  "code": "UNAUTHORIZED"
} as const;
export const sessionSuccess = {
  "user": {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "normalizedPhone": "+8613800138000",
    "createdAt": "2025-07-16T00:00:00.000Z",
    "lastLoginAt": "2025-07-16T00:00:00.000Z",
    "isLoggedIn": true,
    "hasFullAccess": false
  }
} as const;
export const verifyCodeErrorAttemptsExceeded = {
  "error": "验证码错误或已过期",
  "code": "ATTEMPTS_EXCEEDED"
} as const;
export const verifyCodeErrorExpired = {
  "error": "验证码错误或已过期",
  "code": "VERIFICATION_EXPIRED"
} as const;
export const verifyCodeErrorInvalidCode = {
  "error": "验证码错误或已过期",
  "code": "INVALID_CODE"
} as const;
export const verifyCodeErrorParamsRequired = {
  "error": "手机号和验证码不能为空",
  "code": "PARAMS_REQUIRED"
} as const;
export const verifyCodeSuccess = {
  "token": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
  "user": {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "normalizedPhone": "+8613800138000",
    "createdAt": "2025-07-16T00:00:00.000Z",
    "lastLoginAt": "2025-07-16T00:00:00.000Z",
    "isLoggedIn": true,
    "hasFullAccess": false
  }
} as const;

// ── Lookup by endpoint and status ───────────────────────────────────

type EndpointId =
  | 'health'
  | 'send-code'
  | 'verify-code'
  | 'session'
  | 'logout'
  ;

type FixtureKey = keyof typeof fixtureMap;

const fixtureMap = {
  'health-success': healthSuccess,
  'logout-success': logoutSuccess,
  'send-code-error-cooldown': sendCodeErrorCooldown,
  'send-code-error-invalid-phone': sendCodeErrorInvalidPhone,
  'send-code-error-phone-required': sendCodeErrorPhoneRequired,
  'send-code-error-rate-limited': sendCodeErrorRateLimited,
  'send-code-error-sms-unavailable': sendCodeErrorSmsUnavailable,
  'send-code-success-dev': sendCodeSuccessDev,
  'send-code-success': sendCodeSuccess,
  'session-error-expired': sessionErrorExpired,
  'session-error-revoked': sessionErrorRevoked,
  'session-error-unauthorized': sessionErrorUnauthorized,
  'session-success': sessionSuccess,
  'verify-code-error-attempts-exceeded': verifyCodeErrorAttemptsExceeded,
  'verify-code-error-expired': verifyCodeErrorExpired,
  'verify-code-error-invalid-code': verifyCodeErrorInvalidCode,
  'verify-code-error-params-required': verifyCodeErrorParamsRequired,
  'verify-code-success': verifyCodeSuccess,
} as const;

/**
 * Get fixture data by endpoint ID and fixture key.
 * Wraps strict typing over the raw JSON file index.
 */
export function getFixture<K extends keyof typeof fixtureMap>(key: K): (typeof fixtureMap)[K] {
  return fixtureMap[key];
}
