// ── packages/contracts/src/msw/handlers.ts ────────────────────────────
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/contracts/generate.mjs
//
// MSW request handlers. Requires `msw` as a devDependency:
//   npm install --save-dev msw
//
// Usage (MSW 2.x):
//   import { http } from 'msw';
//   import { handlers } from 'packages/contracts/src/msw/handlers';
//   import { setupWorker } from 'msw/browser';
//   setupWorker(...handlers);
//
// For projects without MSW, use fetch-mock.ts instead (pure-fetch adapter).
//

import { http, HttpResponse } from 'msw';
import type { ErrorCode,
  HealthResponse,
  LogoutResponse,
  SendCodeRequest,
  SendCodeResponse,
  SessionResponse,
  User,
  VerifyCodeRequest,
  VerifyCodeResponse } from '../types/api';

// ── Fixture data ───────────────────────────────────────────────────
const healthSuccess = {
  "status": "ok"
} as const;
const logoutSuccess = {
  "success": true
} as const;
const sendCodeErrorCooldown = {
  "error": "发送太频繁，请 42 秒后再试",
  "code": "COOLDOWN"
} as const;
const sendCodeErrorInvalidPhone = {
  "error": "手机号格式不正确",
  "code": "INVALID_PHONE"
} as const;
const sendCodeErrorPhoneRequired = {
  "error": "手机号不能为空",
  "code": "PHONE_REQUIRED"
} as const;
const sendCodeErrorRateLimited = {
  "error": "发送太频繁，请稍后再试",
  "code": "RATE_LIMITED"
} as const;
const sendCodeErrorSmsUnavailable = {
  "error": "短信服务暂不可用，请稍后再试",
  "code": "SMS_UNAVAILABLE"
} as const;
const sendCodeSuccessDev = {
  "success": true,
  "debugCode": "123456"
} as const;
const sendCodeSuccess = {
  "success": true
} as const;
const sessionErrorExpired = {
  "error": "会话已过期",
  "code": "SESSION_EXPIRED"
} as const;
const sessionErrorRevoked = {
  "error": "会话已失效",
  "code": "SESSION_REVOKED"
} as const;
const sessionErrorUnauthorized = {
  "error": "未登录",
  "code": "UNAUTHORIZED"
} as const;
const sessionSuccess = {
  "user": {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "normalizedPhone": "+8613800138000",
    "createdAt": "2025-07-16T00:00:00.000Z",
    "lastLoginAt": "2025-07-16T00:00:00.000Z",
    "isLoggedIn": true,
    "hasFullAccess": false
  }
} as const;
const verifyCodeErrorAttemptsExceeded = {
  "error": "验证码错误或已过期",
  "code": "ATTEMPTS_EXCEEDED"
} as const;
const verifyCodeErrorExpired = {
  "error": "验证码错误或已过期",
  "code": "VERIFICATION_EXPIRED"
} as const;
const verifyCodeErrorInvalidCode = {
  "error": "验证码错误或已过期",
  "code": "INVALID_CODE"
} as const;
const verifyCodeErrorParamsRequired = {
  "error": "手机号和验证码不能为空",
  "code": "PARAMS_REQUIRED"
} as const;
const verifyCodeSuccess = {
  "token": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
  "user": {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "normalizedPhone": "+8613800138000",
    "createdAt": "2025-07-16T00:00:00.000Z",
    "lastLoginAt": "2025-07-16T00:00:00.000Z",
    "isLoggedIn": true,
    "hasFullAccess": false
  }
} as const;

// ── Handlers ─────────────────────────────────────────────────────

export const handlers = [
  http.get('/api/health', () => {
    return HttpResponse.json(healthSuccess);
  }),
  http.post('/api/auth/send-code', () => {
    return HttpResponse.json(sendCodeSuccess);
  }),
  http.post('/api/auth/verify-code', () => {
    return HttpResponse.json(verifyCodeSuccess);
  }),
  http.get('/api/auth/session', () => {
    return HttpResponse.json(sessionSuccess);
  }),
  http.post('/api/auth/logout', () => {
    return HttpResponse.json(logoutSuccess);
  }),
];
