#!/usr/bin/env node
// apps/frontend/scripts/switch-mode.cjs
// 切换 API 模式: node scripts/switch-mode.cjs mock|real
// 写入 .env.local 让 Vite 读取

'use strict';
const fs = require('fs');
const path = require('path');

const mode = process.argv[2];
if (!['mock', 'real'].includes(mode)) {
  console.error('Usage: node scripts/switch-mode.cjs mock|real');
  process.exit(1);
}

const baseUrl = mode === 'real'
  ? (process.env.VITE_API_BASE_URL || 'http://localhost:3000')
  : 'http://localhost:3000';

const content = [
  `# Auto-generated by switch-mode.cjs — do not edit manually`,
  `VITE_API_MODE=${mode}`,
  `VITE_API_BASE_URL=${baseUrl}`,
  '',
].join('\n');

const envPath = path.join(__dirname, '..', '.env.local');
fs.writeFileSync(envPath, content, 'utf8');
console.info(`[switch-mode] Wrote VITE_API_MODE=${mode} to .env.local`);
